worker_processes auto;

events
{
    use epoll;
    worker_connections 51200;
    multi_accept on;
}

http
{
    include mime.types;
    default_type application/octet-stream;
    server
    {
        listen 80;
        server_name ltpp.vip hbnuoj.ltpp.vip 127.0.0.1 localhost
        index index.html;
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;

        #禁止访问的文件或目录
        location ~ ^/(\.user.ini|\.htaccess|\.git|\.env|\.svn|\.project|LICENSE|README.md)
        {
            return 404;
        }

        #一键申请SSL证书验证目录相关设置
        location ~ \.well-known
        {
            allow all;
        }
        
        #禁止在证书验证目录放入敏感文件
        if ( $uri ~ "^/\.well-known/.*\.(php|jsp|py|js|css|lua|ts|go|zip|tar\.gz|rar|7z|sql|bak)$" )
        {
            return 403;
        }

        location ~ .*\.(gif|jpg|jpeg|png|bmp|swf)$ 
        {
            expires      30d;
            error_log /dev/null;
            access_log /dev/null;
        }

        location ~ .*\.(js|css)?$
        {
            expires      30d;
            error_log /dev/null;
            access_log /dev/null;
        }
        access_log  /dev/null;
        error_log  /tmp/nginx.error.log;
    }
}